### PR TITLE
Fix recursive update of parent node tables

### LINKED ISSUE #9: nested RecursiveOpenStructs are not updated in @table
This is the same issue as #5, which wasn't quite fixed.

If I create a RecursiveOpenStruct then change the value in a leaf node somewhere, the @table hash does not get updated.

```ruby
[1] acme »  reos = RecursiveOpenStruct.new(:one => { :two => { :three => :four } })
=> #<RecursiveOpenStruct one={:two=>{:three=>:four}}>
[2] acme »  reos.one.two.three = :five
=> :five
[3] acme »  reos.to_h
=> {
  :one => {
    :two => {
      :three => :five
    }
  }
}
[4] acme »  reos
=> #<RecursiveOpenStruct one={:two=>{:three=>:four}}>
[5] acme »  reos.instance_variable_get(:@table)
=> {
  :one => {
    :two => {
      :three => :four
    }
  }
}
```

Therefore, if you dup `reos` or call `to_json` or anything, without going through `to_h` directly, it does not carry forward the change. This is especially a problem if you have nested RecursiveOpenStructs:

```ruby
[34] acme »  reos = RecursiveOpenStruct.new(:one => RecursiveOpenStruct.new(:two => { :three => '15' }))
=> #<RecursiveOpenStruct one=#<RecursiveOpenStruct two={:three=>"15"}>>
[36] acme »  reos.one.two.three = 15
=> 15
[37] acme »  reos
=> #<RecursiveOpenStruct one=#<RecursiveOpenStruct two={:three=>"15"}>>
[38] acme »  reos.to_h
=> {
           :one => #<RecursiveOpenStruct two={:three=>"15"}>
}
```

Notice the value is still the string '15' instead of the integer.

### PR DESCRIPTION
**Pull request by fervic**
Fixes #9 by keeping a reference of the hash upon initialization instead of creating an empty hash. Only does this if specified in the options hash.

### CODE REVIEW

File: spec/recursive_open_struct_spec.rb [hunk 1]
```diff
@@ -96,16 +96,21 @@
...
       subject { RecursiveOpenStruct.new(hash) }
       before(:each) { subject.blah.blargh = "Janet" }
       it "returns a hash that contains those modifications" do
-        subject.to_h.should == { :blah => { :blargh => "Janet" } }
+        subject.to_h.should == updated_hash
+      end
+
+      it "reflects the change at the root node" do
+        table = subject.instance_variable_get(:@table)
+        table.should == updated_hash
```
Comment (aetherknight) [inline spec/recursive_open_struct_spec.rb]: Instead of violating encapsulation, could you test the behavior that is broken? Eg:
```
expect(subject.dup.to_h) .to eq updated_hash
```
Or in Rspec 2.x syntax:
```
subject.dup.to_h.should == updated_hash
```

I think it would also be good to verify that the original has is not modified. Something like:
```
it "does not modify the original input hash" do
  hash[:blah][:blargh].should == 'Brad'
end
```
You could also implicitly test this if you constantized `hash`, but you would need to ensure that all of its sub-elements are constantized as well (eg, the sub-hash and the string).

**Comment by aetherknight** [comment]
The implementation looks clean and straightforward. Once you make the changes to the tests, I'd be happy to merge it in.

**Comment by fervic** [comment]
@aetherknight I'm glad you suggested to add the test about not modifying the original hash because it is not passing. At the first level it is a different reference, but after that they continue pointing to the same structure. I don't know if the only option would be to store the references on a separate variable that is recursively passed to the initialize method.

**Comment by fervic** [comment]
I think I found a solution by deep duplicating the first input hash (when the flag is set to false).

I just tried it using active\_supports deep\_dup just to be able verify it quickly. I will now work in bringing this logic into the class and then push for you to review.

**Comment by fervic** [comment]
@aetherknight it should be good to go now. Please review and let me know.

**Comment by fervic** [comment]
@aetherknight it should be good to go now. Please review and let me know. At the end it wasn't as simple as I initially thought.

File: lib/recursive_open_struct.rb [hunk 2]
```diff
@@ -92,4 +105,25 @@ def display_recursive_open_struct(io, ostrct_or_hash, indent_level, recursion_li
...
   end
 
+  private
+  
+  def deep_dup(obj, visited=[])
+    if obj.is_a?(Hash)
+      obj.each_with_object({}) do |(key, value), h|
+        h[key] = value_or_deep_dup(value, visited)
+      end
+    elsif obj.is_a?(Array)
```
Comment (aetherknight) [inline lib/recursive_open_struct.rb]: Hmm, what if `recurse_over_arrays` is false? I think a good case can be made that when `recurse_over_arrays` is false, that the `deep_dup` should stop with the original hash tree --- it shouldn't `dup` or recurse into any Arrays it encounters.

File: lib/recursive_open_struct.rb [hunk 3]
```diff
@@ -92,4 +105,25 @@ def display_recursive_open_struct(io, ostrct_or_hash, indent_level, recursion_li
...
+        arr << value_or_deep_dup(value, visited)
+      end
+    else
+      obj
+    end
+  end
+
+  def value_or_deep_dup(value, visited)
+    obj_id = value.object_id
+    visited.include?(obj_id) ? value : deep_dup(value, visited << obj_id)
```
Comment (aetherknight) [inline lib/recursive_open_struct.rb]: :+1: to avoiding recursion loops.

**Comment by aetherknight** [comment]
I'm going to merge this in, and then I'll address the `recurse_over_arrays` x `deep_dup` case before cutting a new release. Thanks for your hard work!
